Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Curso_De_ASP_NET_Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace Curso_De_ASP_NET_Core.Controllers
{
    public class AlumnoController : Controller
    {
        [Route("Alumno/Index")]
        [Route("Alumno/Index/{AlumnoId}")]
        public IActionResult Index(string id)
        {
            if (!string.IsNullOrWhiteSpace(id))
            {
                var alumno = from alum in _context.Alumnos
                                 where alum.Id == id
                                 select alum;
                return View(alumno.SingleOrDefault());
            }
            else
            {
                return View("MultiAlumno", _context.Alumnos);
            }

        }
        public IActionResult MultiAlumno()
        {
            ViewBag.CosaDinamica = "La monja";
            ViewBag.Fecha = DateTime.Now;
            return View("MultiAlumno", _context.Alumnos);
        }
        
         #region Crear Alumnos
        public IActionResult Create()
        {
            ViewBag.Fecha = DateTime.Now;

            return View();
        }


        [HttpPost]
        public IActionResult Create(Alumno alumno)
        {
            ViewBag.Fecha = DateTime.Now;

            if (ModelState.IsValid)
            {

                var escuela = _context.Escuelas.FirstOrDefault();
                alumno.EscuelaId = escuela.Id;
                _context.Alumnos.Add(alumno);
                _context.SaveChanges();
                ViewBag.MensajeExra = "Curso Creado";
                return View("Index", alumno);
            }
            else
            {
                return View(alumno);
            }
        }
        #endregion

        #region Actualizar Alumno
        public IActionResult Update()
        {
            ViewBag.Fecha = DateTime.Now;

            return View();
        }


        [HttpPost]
        [Route("Alumno/Update")]
        [Route("Alumno/Update/{alumnoId}")]
        public IActionResult Update(Alumno alumno)
        {
            ViewBag.Fecha = DateTime.Now;

            if (ModelState.IsValid)
            {

                var escuela = _context.Escuelas.FirstOrDefault();
                alumno.EscuelaId = escuela.Id;
                _context.Alumnos.Update(alumno);
                _context.SaveChanges();
                ViewBag.MensajeExra = "alumno Actualizada";
                return View("Update", alumno);
            }
            else
            {
                return View(alumno);
            }
        }
        #endregion
        private EscuelaContext _context;
        public AlumnoController(EscuelaContext context)
        {
            _context = context;
        }

    }
}

Controllers/AsignaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Curso_De_ASP_NET_Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace Curso_De_ASP_NET_Core.Controllers
{
    public class AsignaturaController : Controller
    {
        /*public IActionResult Index()
        {
            return View( _context.Asignaturas.FirstOrDefault());
        }*/
        [Route("Asignatura/Index")]
        [Route("Asignatura/Index/{asignaturaId}")]
        public IActionResult Index(string asignaturaId)
        {
            if (!string.IsNullOrWhiteSpace(asignaturaId))
            {
                var asignatura = from asig in _context.Asignaturas
                                 where asig.Id == asignaturaId
                                 select asig;
                return View(asignatura.SingleOrDefault());
            }
            else
            {
                return View("MultiAsignatura", _context.Asignaturas);
            }

        }
        public IActionResult MultiAsignatura()
        {
            ViewBag.CosaDinamica = "La Monja";
            ViewBag.Fecha = DateTime.Now;

            return View("MultiAsignatura", _context.Asignaturas);
        }

        #region Crear Asignatura
        public IActionResult Create()
        {
            ViewBag.Fecha = DateTime.Now;

            return View();
        }


        [HttpPost]
        public IActionResult Create(Asignatura asignatura)
        {
            ViewBag.Fecha = DateTime.Now;

            if (ModelState.IsValid)
            {

                var escuela = _context.Escuelas.FirstOrDefault();
                asignatura.EscuelaId = escuela.Id;
                _context.Asignaturas.Add(asignatura);
                _context.SaveChanges();
                ViewBag.MensajeExra = "Asignatura Creada";
                return View("Index", asignatura);
            }
            else
            {
                return View(asignatura);
            }
        }
        #endregion

        #region Actualizar Asignatura
        public IActionResult Update()
        {
            ViewBag.Fecha = DateTime.Now;

            return View();
        }


        [HttpPost]
        [Route("Asignatura/Update")]
        [Route("Asignatura/Update/{asignaturaId}")]
        public IActionResult Update(Asignatura asignatura)
        {
            ViewBag.Fecha = DateTime.Now;

            if (ModelState.IsValid)
            {

                var escuela = _context.Escuelas.FirstOrDefault();
                asignatura.EscuelaId = escuela.Id;
                _context.Asignaturas.Update(asignatura);
                _context.SaveChanges();
                ViewBag.MensajeExra = "Asignatura Actualizada";
                return View("Update", asignatura);
            }
            else
            {
                return View(asignatura);
            }
        }
        #endregion

        private EscuelaContext _context;
        public AsignaturaController(EscuelaContext context)
        {
            _context = context;
        }
    }
}

Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Curso_De_ASP_NET_Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace Curso_De_ASP_NET_Core.Controllers
{
    public class CursoController : Controller
    {
        [Route("Curso/Index")]
        [Route("Curso/Index/{CursoId}")]
        public IActionResult Index(string id)
        {
            if (!string.IsNullOrWhiteSpace(id))
            {
                var curso = from cur in _context.Cursos
                            where cur.Id == id
                            select cur;
                return View(curso.SingleOrDefault());
            }
            else
            {
                return View("MultiCurso", _context.Cursos);
            }

        }
        public IActionResult MultiCurso()
        {
            ViewBag.CosaDinamica = "La monja";
            ViewBag.Fecha = DateTime.Now;
            return View("MultiCurso", _context.Cursos);
        }
        #region Crear Curso
        public IActionResult Create()
        {
            ViewBag.Fecha = DateTime.Now;

            return View();
        }


        [HttpPost]
        public IActionResult Create(Curso curso)
        {
            ViewBag.Fecha = DateTime.Now;

            if (ModelState.IsValid)
            {

                var escuela = _context.Escuelas.FirstOrDefault();
                curso.EscuelaId = escuela.Id;
                _context.Cursos.Add(curso);
                _context.SaveChanges();
                ViewBag.MensajeExra = "Curso Creado";
                return View("Index", curso);
            }
            else
            {
                return View(curso);
            }
        }
        #endregion

        #region Actualizar Curso
        public IActionResult Update()
        {
            ViewBag.Fecha = DateTime.Now;

            return View();
        }


        [HttpPost]
        [Route("Curso/Update")]
        [Route("Curso/Update/{cursoId}")]
        public IActionResult Update(Curso curso)
        {
            ViewBag.Fecha = DateTime.Now;

            if (ModelState.IsValid)
            {

                var escuela = _context.Escuelas.FirstOrDefault();
                curso.EscuelaId = escuela.Id;
                _context.Cursos.Update(curso);
                _context.SaveChanges();
                ViewBag.MensajeExra = "curso Actualizada";
                return View("Update", curso);
            }
            else
            {
                return View(curso);
            }
        }
        #endregion

        #region Actualizar Curso
        public IActionResult Delete()
        {
            ViewBag.Fecha = DateTime.Now;

            return View();
        }


        [HttpPost]
        [Route("Curso/Delete")]
        [Route("Curso/Delete/{cursoId}")]
        public IActionResult Delete(Curso curso)
        {
            ViewBag.Fecha = DateTime.Now;

            if (ModelState.IsValid)
            {

                var escuela = _context.Escuelas.FirstOrDefault();
                curso.EscuelaId = escuela.Id;
                _context.Cursos.Remove(curso);
                _context.SaveChanges();
                ViewBag.MensajeExra = "curso Borrado";
                return View("Delete", curso);
            }
            else
            {
                return View(curso);
            }
        }
        #endregion
        private EscuelaContext _context;
        public CursoController(EscuelaContext context)
        {
            _context = context;
        }

    }
}

Controllers/EscuelaController.cs
using System.Linq;
using System;
using Curso_De_ASP_NET_Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace Curso_De_ASP_NET_Core.Controllers
{
    public class EscuelaController : Controller
    {
        public IActionResult  Index()
        {
            /*var escuela = new Escuela();
            escuela.AñoDeCreación=2013;
            escuela.UniqueId = Guid.NewGuid().ToString();
            escuela.Nombre="Pixeles Eschool";
            escuela.Ciudad="Merida";
            escuela.Pais="México";
            escuela.Dirección="Calle 31 x 14 y 12";
            escuela.TipoEscuela=TiposEscuela.Secundaria;*/

            var escuela = _context.Escuelas.FirstOrDefault();
            

            ViewBag.CosaDinamica = "La monja";

            return View(escuela);
        }

        
        private EscuelaContext _context;
        public EscuelaController(EscuelaContext context)
        {
            _context = context;
        }
    }
}

Views/Shared/EscuelaBaseSimple.cshtml
@model ObjetoEscuelaBase

<p>
    Nombre:@Model.Nombre <br/>
    Id : @Model.Id
</p>

Views/Shared/ListaCurso.cshtml
@*
@model List<ObjetoEscuelaBase>
*@

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col"> Nombre </th>
            <th scope="col"> Id </th>
            <th scope="col">Dirección</th>
            <th scope="col">Tipo de jornada</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>@obj.Nombre</td>
                <td>@obj.Id</td>
                <td>@obj.Dirección</td>
                <td>@obj.Jornada</td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/ListaObjetosEscuela.cshtml
@*
@model List<ObjetoEscuelaBase>
*@

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col"> Nombre </th>
            <th scope="col"> Id </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>@obj.Nombre</td>
                <td>@obj.Id</td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/Simple.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <img style="opacity: 1;" src="~/images/descarga.png" width="250" height="250">
    <title>@ViewData["Title"] - Escuela</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
   
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Curso_De_ASP_NET_Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <ul>
    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumno"
                                asp-action="MultiAlumno">MultiAlumno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumno"
                                asp-action="Create">CrearAlumno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumno"
                                asp-action="Update">ActualizarAlumno</a>
                        </li>
                        </ul>
                        <ul>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asignatura"
                                asp-action="MultiAsignatura">MultiAsignatura</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asignatura"
                                asp-action="Create">CrearAsignatura</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asignatura"
                                asp-action="Update">ActualizarAsignatura</a>
                        </li>
                        </ul>
                        
                        <ul>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso"
                                asp-action="MultiCurso">MultiCurso</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso"
                                asp-action="Create">CrearCurso</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso"
                                asp-action="Update">ActualizarCurso</a>
                        </li>

                        </ul>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Escuela"
                                asp-action="Index">Escuela</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Curso_De_ASP_NET_Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Curso_De_ASP_NET_Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Escuela" asp-action="Index">Escuela</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <i>Render Body</i>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Curso_De_ASP_NET_Core - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>